name: C++ Build and SonarQube Scan

on:
  push:
    branches:
      - master  # Change to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ unzip

      - name: Build C++ project
        run: |
          g++ -o main "Final Project"/Main.cpp

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optional: Fail job if Quality Gate fails
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   with:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
